#!/bin/bash
set -ev
mkdir sleef.build
cd sleef.build
export CC=clang-11
export CXX=clang++-11
cmake -G Ninja -DRUNNING_ON_TRAVIS=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DSLEEF_SHOW_CONFIG=1 -DEMULATOR=qemu-aarch64 -DENFORCE_TESTER3=TRUE -DBUILD_QUAD=TRUE -DBUILD_DFT=TRUE -DBUILD_INLINE_HEADERS=TRUE -DENABLE_ALTDIV=TRUE -DENABLE_ALTSQRT=TRUE -DENFORCE_SVE=TRUE ..
