source 'https://rubygems.org'

gem "jekyll", "~> 4.3.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.8.2" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

gem "jekyll-relative-links", "~> 0.7.0" # for relative path to images and sources
